//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.DonationLog = new HashSet<DonationLog>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int DonorSexId { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public Nullable<int> ABOBloodGroupId { get; set; }
        public Nullable<int> RhBloodGroupId { get; set; }
    
        public virtual ABOBloodGroup ABOBloodGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationLog> DonationLog { get; set; }
        public virtual DonorSex DonorSex { get; set; }
        public virtual RhBloodGroup RhBloodGroup { get; set; }
    }
}
