//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public int DonationCenterId { get; set; }
        public string PhoneNumber1 { get; set; }
        public string Comments { get; set; }
    
        public virtual DonationCenter DonationCenter { get; set; }
    }
}
